server:
  servlet:
    context-path: /produdoro/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://produdoroDevUser:WvfWkvlgScvc3Omr@cluster0.yhxrlbh.mongodb.net/Cluster0?retryWrites=true&w=majority}
      auto-index-creation: true